sudo: false

language: python

python:
  - 3.6
  - nightly

install:
  - pip install '.[ci]'

script:
  - nosetests -v --with-coverage --cover-package=snv_spectrum --cover-xml

after_success:
  - codecov

notifications:
  email: false

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
